name: CI

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

env: 
  dotnet-version: 8.0.x

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [net8.0, net462]
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet-version }}
 
    - name: Restore
      run: dotnet restore Fake4DataverseFree.sln

    - name: Build ${{ matrix.framework }}
      run: dotnet build Fake4DataverseFree.sln --configuration Debug --framework ${{ matrix.framework }} --no-restore
        
    - name: Test ${{ matrix.framework }}
      run: dotnet test Fake4DataverseFree.sln --configuration Debug --framework ${{ matrix.framework }} --no-build --verbosity normal
      continue-on-error: true
